FROM docker.io/library/python:latest

WORKDIR /design_of_www
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

expose 5000

CMD ["gunicorn", "-b", "0.0.0.0:5000", "--chdir", "src", "wsgi:app"]
